"""Shared types and conventions for the stereo-spot video processing pipeline."""

from .interfaces import (
    JobStore,
    ObjectStorage,
    OperatorLinksProvider,
    QueueMessage,
    QueueReceiver,
    QueueSender,
    SegmentCompletionStore,
)
from .keys import (
    build_segment_key,
    parse_input_key,
    parse_output_segment_key,
    parse_segment_key,
)
from .logging_config import configure_logging
from .models import (
    ChunkingPayload,
    CreateJobRequest,
    CreateJobResponse,
    DeletionPayload,
    IngestPayload,
    IngestPayloadUnion,
    Job,
    JobEvent,
    JobListItem,
    JobStatus,
    JobTableChange,
    PresignedPlaybackResponse,
    ReassemblyPayload,
    SegmentCompletion,
    SegmentCompletionInsert,
    SegmentKeyPayload,
    StereoMode,
    VideoWorkerPayload,
    YoutubeIngestPayload,
    parse_ingest_payload,
)

__version__ = "0.1.0"
__all__ = [
    "configure_logging",
    "JobStore",
    "OperatorLinksProvider",
    "ObjectStorage",
    "QueueMessage",
    "QueueReceiver",
    "QueueSender",
    "SegmentCompletionStore",
    "build_segment_key",
    "parse_input_key",
    "parse_output_segment_key",
    "parse_segment_key",
    "ChunkingPayload",
    "CreateJobRequest",
    "CreateJobResponse",
    "DeletionPayload",
    "IngestPayload",
    "IngestPayloadUnion",
    "Job",
    "JobEvent",
    "JobListItem",
    "JobStatus",
    "JobTableChange",
    "SegmentCompletionInsert",
    "PresignedPlaybackResponse",
    "ReassemblyPayload",
    "SegmentCompletion",
    "SegmentKeyPayload",
    "StereoMode",
    "VideoWorkerPayload",
    "YoutubeIngestPayload",
    "parse_ingest_payload",
]
