"""Platform adapter facade: selects cloud implementations by PLATFORM env (aws | gcp)."""

from .env_config import (
    chunking_queue_receiver_from_env,
    chunking_queue_sender_from_env,
    deletion_queue_receiver_from_env,
    deletion_queue_sender_from_env,
    inference_invocations_store_from_env,
    ingest_queue_receiver_from_env,
    ingest_queue_receiver_from_env_or_none,
    ingest_queue_sender_from_env,
    ingest_queue_sender_from_env_or_none,
    input_bucket_name,
    job_events_normalizer_from_env,
    job_events_queue_receiver_from_env_or_none,
    job_store_from_env,
    object_storage_from_env,
    operator_links_from_env,
    output_bucket_name,
    output_events_queue_receiver_from_env,
    push_subscriptions_store_from_env_or_none,
    reassembly_queue_receiver_from_env,
    reassembly_queue_sender_from_env,
    reassembly_triggered_lock_from_env,
    segment_completion_store_from_env,
    segment_output_queue_receiver_from_env,
    video_worker_queue_receiver_from_env,
    video_worker_queue_sender_from_env,
)

__all__ = [
    "chunking_queue_receiver_from_env",
    "chunking_queue_sender_from_env",
    "deletion_queue_receiver_from_env",
    "deletion_queue_sender_from_env",
    "inference_invocations_store_from_env",
    "ingest_queue_receiver_from_env",
    "ingest_queue_receiver_from_env_or_none",
    "ingest_queue_sender_from_env",
    "ingest_queue_sender_from_env_or_none",
    "input_bucket_name",
    "job_events_normalizer_from_env",
    "job_events_queue_receiver_from_env_or_none",
    "job_store_from_env",
    "object_storage_from_env",
    "operator_links_from_env",
    "output_bucket_name",
    "output_events_queue_receiver_from_env",
    "push_subscriptions_store_from_env_or_none",
    "reassembly_queue_receiver_from_env",
    "reassembly_queue_sender_from_env",
    "reassembly_triggered_lock_from_env",
    "segment_completion_store_from_env",
    "segment_output_queue_receiver_from_env",
    "video_worker_queue_receiver_from_env",
    "video_worker_queue_sender_from_env",
]
