# Generate Helm values from Terraform outputs so the stereo-spot chart receives
# queue URLs, bucket names, and table names. Argo CD (or helm install) uses
# this file together with values.yaml. ECR repo URIs are added in Step 4.4.
resource "local_file" "helm_values" {
  filename = "${path.module}/../helm/values-from-terraform.yaml"
  content  = <<-EOT
# Generated by Terraform (packages/aws-infra). Do not edit by hand.
# Overrides/supplements packages/helm/values.yaml with resource names from this stack.

aws:
  inputBucketName: ${aws_s3_bucket.input.id}
  outputBucketName: ${aws_s3_bucket.output.id}
  jobsTableName: ${aws_dynamodb_table.jobs.name}
  segmentCompletionsTableName: ${aws_dynamodb_table.segment_completions.name}
  reassemblyTriggeredTableName: ${aws_dynamodb_table.reassembly_triggered.name}

queues:
  chunking: ${aws_sqs_queue.chunking.url}
  videoWorker: ${aws_sqs_queue.video_worker.url}
  reassembly: ${aws_sqs_queue.reassembly.url}

global:
  awsRegion: ${local.region}
EOT
}
